In [1]:
import numpy as np
import numpy.linalg as la

In [6]:
W = [[0.58, 0.24],
     [0.24, 0.72]]

(l1, l2), q = la.eigh(W)
s = np.array([[l1,  0],
              [ 0, l2]])
print(f'Q={q}\nΛ={s}\nQ^-1={q.T}')  
# these are the correct values of Q and Q^-1 (they are wrong in exercise sheet)

Q=[[-0.8  0.6]
 [ 0.6  0.8]]
Λ=[[0.4 0. ]
 [0.  0.9]]
Q^-1=[[-0.8  0.6]
 [ 0.6  0.8]]


In [3]:
q @ s @ q.T

array([[0.58, 0.24],
       [0.24, 0.72]])

In [4]:
s30 = s**30
s30

array([[1.15292150e-12, 0.00000000e+00],
       [0.00000000e+00, 4.23911583e-02]])

In [5]:
w30 = q @ s30 @ q.T
print(w30)
# with the correct eigenvalue decomposition, W^30 is as follows
# please note that the absolute values are same as with when you
# calculate using the matrices given on the exercise sheet, but the
# signs are all positive here (instead of two minus signs)

[[0.01526082 0.02034776]
 [0.02034776 0.02713034]]
